version: '3.8'

services:
  app_{{CLIENT}}:
    container_name: app_{{CLIENT}}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "{{PORT}}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: {{MYSQLPORT}}
      DB_DATABASE: {{DB_NAME}}
      DB_USERNAME: {{DB_USERNAME}}
      DB_PASSWORD: '{{DB_PASSWD}}'

  db:
    container_name: db_{{CLIENT}}
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: {{DB_ROOTPASSWD}}
      MYSQL_DATABASE: {{DB_NAME}}
      MYSQL_USER: {{DB_USERNAME}}
      MYSQL_PASSWORD: '{{DB_PASSWD}}'
    ports:
      - "{{MYSQLPORT}}:{{MYSQLPORT}}"
    volumes:
      - dbdata_{{CLIENT}}:/var/lib/mysql

  phpmyadmin_{{CLIENT}}:
    container_name: phpmyadmin_{{CLIENT}}
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "{{PMA_PORT}}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: {{DB_ROOTPASSWD}}
    depends_on:
      - db

volumes:
  dbdata_{{CLIENT}}:
