version: '3.8'

services:
  app_{{CLIENT}}:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "{{PORT}}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_db
      - DB_USERNAME=laravel_usr
      - DB_PASSWORD='L@r#vel@123'

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Admin@321@123'
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_usr
      MYSQL_PASSWORD: 'L@r#vel@123'
    ports:
      - "{{MYSQLPORT}}:3306"
    volumes:
      - dbdata_{{CLIENT}}:/var/lib/mysql

  phpmyadmin_{{CLIENT}}:
    image: phpmyadmin/phpmyadmin
    ports:
      - "{{PMA_PORT}}:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD='Admin@321@123'
    depends_on:
      - db

volumes:
  dbdata_{{CLIENT}}:
